from datetime import datetime


def get_mock_locations() -> list[str]:
    return [
        "BOISE NORTH",
        "HEYBURN",
        "MISSOULA EAST",
        "PHOENIX WEST",
        "TEXARKANA",
        "TWIN FALLS",
    ]


def build_mock_snapshot():
    return {
        "meta": {
            "last_updated": datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"),
            "source": "mock",
            "status": "healthy",
            "message": "Showing seeded dashboard data while Databricks credentials are being added. Call data is only shown when live query results are available.",
            "location": "ALL LOCATIONS",
            "limit": 25,
        },
        "kpis": [
            {"label": "High-risk customers", "value": "1,284", "delta": "+8.4%", "tone": "risk"},
            {"label": "Repeat trouble calls", "value": "3,912", "delta": "+4.1%", "tone": "warning"},
            {"label": "Truck rolls / 30d", "value": "864", "delta": "-2.7%", "tone": "good"},
            {"label": "Service health score", "value": "72", "delta": "-5 pts", "tone": "warning"},
            {"label": "Competitive risk markets", "value": "11", "delta": "+2", "tone": "risk"},
        ],
        "signal_mix": [
            {"label": "Repeat outages", "value": 31},
            {"label": "Trouble calls", "value": 26},
            {"label": "TRR modem distress", "value": 19},
            {"label": "Truck rolls", "value": 14},
            {"label": "Appointments", "value": 10},
        ],
        "call_history": {"summary": [], "segments": []},
        "modem_health": {
            "summary": [
                {"label": "Accounts with telemetry", "value": "42", "delta": "Mock modem cache sample", "tone": "warning"},
                {"label": "Connected modems", "value": "39", "delta": "Latest valid IP sample", "tone": "good"},
                {"label": "Latest modem sample", "value": "2026-05-15 12:00 UTC", "delta": "Mock middleware refresh", "tone": "warning"},
            ],
            "modems": [
                {
                    "geo": "Boise North",
                    "customer_id": "A-104923",
                    "modem_mac": "AA:BB:CC:DD:EE:01",
                    "ip": "10.20.30.40",
                    "last_seen": "2026-05-15 11:53 UTC",
                    "usint": "10500220",
                    "status": "Online",
                },
                {
                    "geo": "Phoenix West",
                    "customer_id": "A-204166",
                    "modem_mac": "AA:BB:CC:DD:EE:02",
                    "ip": "10.20.30.41",
                    "last_seen": "2026-05-15 11:49 UTC",
                    "usint": "204166",
                    "status": "Online",
                },
                {
                    "geo": "Twin Falls",
                    "customer_id": "A-992451",
                    "modem_mac": "AA:BB:CC:DD:EE:03",
                    "ip": "",
                    "last_seen": "2026-05-15 09:18 UTC",
                    "usint": "992451",
                    "status": "Offline",
                },
            ],
        },
        "geo_summary": [
            {
                "geo": "Boise North",
                "flagged_accounts": 184,
                "avg_risk": 91,
                "high_risk_count": 66,
                "contactable_count": 180,
                "top_driver": "Support Interaction (Calls & Contacts)",
                "risk_tier": "Tier 1",
                "recommended_action": "Plant sweep + proactive outreach",
            },
            {
                "geo": "Phoenix West",
                "flagged_accounts": 162,
                "avg_risk": 88,
                "high_risk_count": 58,
                "contactable_count": 159,
                "top_driver": "Past Truckrolls",
                "risk_tier": "Tier 1",
                "recommended_action": "Appointment backlog reset",
            },
            {
                "geo": "Twin Falls",
                "flagged_accounts": 113,
                "avg_risk": 76,
                "high_risk_count": 27,
                "contactable_count": 110,
                "top_driver": "Promotion & Discounts",
                "risk_tier": "Tier 2",
                "recommended_action": "Watch list + SMS update",
            },
            {
                "geo": "Missoula East",
                "flagged_accounts": 74,
                "avg_risk": 61,
                "high_risk_count": 11,
                "contactable_count": 72,
                "top_driver": "High Charges (Pricing & Bill Changes)",
                "risk_tier": "Tier 3",
                "recommended_action": "Monitor",
            },
        ],
        "high_risk_customers": [
            {
                "customer_id": "A-104923",
                "geo": "Boise North",
                "churn_probability": 96.0,
                "risk_score": 96,
                "drivers": "3 calls, modem distress, outage cluster",
                "last_event": "2h ago",
                "next_action": "Outbound call + expedite truck roll",
                "phone_number": "208-555-0142",
                "modem_mac": "AA:BB:CC:DD:EE:01",
                "modem_ip": "10.20.30.40",
                "modem_last_seen": "2026-05-15 11:53 UTC",
                "modem_usint": "10500220",
                "modem_status": "Online",
            },
            {
                "customer_id": "A-204166",
                "geo": "Phoenix West",
                "churn_probability": 93.0,
                "risk_score": 93,
                "drivers": "2 truck rolls, low NPS area",
                "last_event": "5h ago",
                "next_action": "Supervisor review",
                "phone_number": "623-555-0199",
                "modem_mac": "AA:BB:CC:DD:EE:02",
                "modem_ip": "10.20.30.41",
                "modem_last_seen": "2026-05-15 11:49 UTC",
                "modem_usint": "204166",
                "modem_status": "Online",
            },
            {
                "customer_id": "A-992451",
                "geo": "Twin Falls",
                "churn_probability": 88.0,
                "risk_score": 88,
                "drivers": "2 outages, appointment slip",
                "last_event": "7h ago",
                "next_action": "SMS apology + credit check",
                "phone_number": "208-555-0177",
                "modem_mac": "AA:BB:CC:DD:EE:03",
                "modem_ip": "",
                "modem_last_seen": "2026-05-15 09:18 UTC",
                "modem_usint": "992451",
                "modem_status": "Offline",
            },
            {
                "customer_id": "A-552061",
                "geo": "Boise North",
                "churn_probability": 86.0,
                "risk_score": 86,
                "drivers": "4 calls in 90d, poor node health",
                "last_event": "11h ago",
                "next_action": "Priority queue routing",
                "phone_number": "208-555-0110",
                "modem_mac": "",
                "modem_ip": "",
                "modem_last_seen": "",
                "modem_usint": "",
                "modem_status": "Unavailable",
            },
        ],
        "playbooks": [
            {
                "tier": "Tier 1",
                "title": "Immediate field + customer action",
                "detail": "Nodes with low health, high repeat contacts, and elevated churn ranking trigger operations review and same-day communications.",
            },
            {
                "tier": "Tier 2",
                "title": "Proactive outreach",
                "detail": "High-friction pockets receive targeted messaging, appointment updates, and watch-list monitoring.",
            },
            {
                "tier": "Tier 3",
                "title": "Monitor",
                "detail": "Stable but watch-listed geos remain visible for trend movement and campaign planning.",
            },
        ],
    }
