apiVersion: v1
kind: ConfigMap
metadata:
  name: service-churn-dashboard-scheduler-config
  namespace: service-churn-dev
data:
  DATABRICKS_HOST: "https://adb-2499533172944623.3.azuredatabricks.net"
  DATABRICKS_WAREHOUSE_ID: "926835bd268bdeb0"

  TARGET_SQL_SERVER: "sql-uatproduct.uat.corp.cableone.net"
  TARGET_SQL_DATABASE: "ServiceChurnDashboard"
  TARGET_SQL_DRIVER: "ODBC Driver 18 for SQL Server"
  TARGET_SQL_ENCRYPT: "yes"
  TARGET_SQL_TRUST_SERVER_CERTIFICATE: "yes"

  SOURCE_SQL_SERVER: "sql-productdbu.uat.corp.cableone.net"
  SOURCE_SQL_DATABASE: "newbacondata"
  SOURCE_SQL_DRIVER: "ODBC Driver 18 for SQL Server"
  SOURCE_SQL_ENCRYPT: "no"
  SOURCE_SQL_TRUST_SERVER_CERTIFICATE: "yes"

  DBX_HTTP_MAX_CONCURRENT_REQUESTS: "6"
  RES_CHURN_INSERT_CHUNK_SIZE: "1000"
  COM_CHURN_INSERT_CHUNK_SIZE: "1000"
  CALL_TABLE_INSERT_CHUNK_SIZE: "1000"
  CHURN_STAGE_WORKERS: "8"
  CALL_TABLE_STAGE_WORKERS: "8"
  TOP_LEVEL_DATA_FETCH_WORKERS: "8"
  RESUME_PARTIAL_RUNS: "false"
