apiVersion: v1
kind: Secret
metadata:
  name: service-churn-dashboard-scheduler-secret
  namespace: service-churn-dev
type: Opaque
stringData:
  DATABRICKS_TOKEN: "replace-with-databricks-token"
  TARGET_SQL_USERNAME: "replace-with-target-sql-username"
  TARGET_SQL_PASSWORD: "replace-with-target-sql-password"
  SOURCE_SQL_USERNAME: "replace-with-source-sql-username"
  SOURCE_SQL_PASSWORD: "replace-with-source-sql-password"
